### ISSUE TITLE
Rails 5 (beta 3)

### ISSUE THREAD

**Issue by kevinvangelder** [jackc/tod#34]
I know you don't officially support Rails 5 yet, but I wanted to let you know that I ran into some issues when trying to use it.
# Date.at

```
Date.today.at Tod::TimeOfDay.new 8
NoMethodError: undefined method `at' for Thu, 24 Mar 2016:Date
```
# ActiveRecord Serialize + Time Zone

```
Tod::TimeOfDay.parse("8:00 AM")
#<Tod::TimeOfDay:0x007f98504f3018 @hour=8, @minute=0, @second=0, @second_of_day=28800>
```

This is great. If you put it into a postgress `:time` field it gets translated from EST to UTC, `03:00:00`, also great. But when you pull it out again it re-applies the -5 time zone adjustment and displays `22:00:00`. :(

I'm going to end up implementing my own (simplified string-based) class, so don't rush to fix these on my account, but I figured you'd want to know about them.

**Comment by jackc** [comment]
Sorry I took so long to look at this.

I wasn't able to reproduce a `Date.at` issue. If you upgraded from a much older version of tod you might be missing a `require 'tod/core_extensions'`. tod doesn't automatically monkey patch core types anymore.

I also couldn't reproduce the serialization problem. Maybe it was fixed in 5.0.0.rc1?

If you have any test cases that can reproduce these issues I'll try to look at it.

**Comment by bigbadmachine** [comment]
@kevinvangelder what did you end up doing to fix this issue? 
 I am in the middle of upgrading to Rails 5 (5.0.0.1) now and I get the same issue using a postgres `:time` field.

@jackc are there plans to update this gem for Rails 5.0?

Model:
`#  start_time    :time`
`serialize :start_time, ::Tod::TimeOfDay`

Console:
`m = Model.new( start_time: "12:00pm" )`
`m.start_time`
` => #<Tod::TimeOfDay:0x007fe864ee9b30 @hour=7, @minute=0, @second=0, @second_of_day=25200>`
`m.save`
`m.start_time`
` => #<Tod::TimeOfDay:0x007fe85f90ef80 @hour=2, @minute=0, @second=0, @second_of_day=7200>`

**Comment by kevinvangelder** [comment]
@bigbadmachine In the end I implemented my own simplified string-only time class. The project I was working on was for a fixed-location tool so it will never need timezone support. If you'd like I can track the code down and throw it in a gist for you.

**Comment by bigbadmachine** [comment]
That would be great if you could.  I will get back to work on that issue tomorrow.
Thanks.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Kevin VanGelder <notifications@github.com> Date: 11/21/16  1:08 PM  (GMT-05:00) To: jackc/tod <tod@noreply.github.com> Cc: Scott Shervington <scott@bigbadmachine.com>, Mention <mention@noreply.github.com> Subject: Re: [jackc/tod] Rails 5 (beta 3) (#34) 
@bigbadmachine In the end I implemented my own simplified string-only time class. The project I was working on was for a fixed-location tool so it will never need timezone support. If you'd like I can track the code down and throw it in a gist for you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jackc/tod","title":"jackc/tod","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jackc/tod"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kevinvangelder in #34: @bigbadmachine In the end I implemented my own simplified string-only time class. The project I was working on was for a fixed-location tool so it will never need timezone support. If you'd like I can track the code down and throw it in a gist for you."}],"action":{"name":"View Issue","url":"https://github.com/jackc/tod/issues/34#issuecomment-262019051"}}}

**Comment by kevinvangelder** [comment]
https://gist.github.com/kevinvangelder/7682bfb588545cadcbacb690a34b0b24

**Comment by jackc** [comment]
Do either of you have code I can run to reproduce this? I still can't get it to happen in the test suite or a pry session on Rails 5.0.01 and latest tod.

```
jack@edi:~/dev/tod$ pry -Ilib
[1] pry(main)> require 'tod'
=> true
[2] pry(main)> require 'active_record'
=> true
[3] pry(main)> ActiveRecord::Base.establish_connection adapter: 'postgresql', database: 'tod_test'
=> #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x0055d30a607b50
 @automatic_reconnect=true,
 @available=
  #<ActiveRecord::ConnectionAdapters::ConnectionPool::ConnectionLeasingQueue:0x0055d30a607998
   @cond=
    #<MonitorMixin::ConditionVariable:0x0055d30a607948
     @cond=#<Thread::ConditionVariable:0x0055d30a607920>,
     @monitor=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x0055d30a607b50 ...>>,
   @lock=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x0055d30a607b50 ...>,
   @num_waiting=0,
   @queue=[]>,
 @checkout_timeout=5,
 @connections=[],
 @mon_count=0,
 @mon_mutex=#<Thread::Mutex:0x0055d30a607ab0>,
 @mon_owner=nil,
 @new_cons_enabled=true,
 @now_connecting=0,
 @reaper=#<ActiveRecord::ConnectionAdapters::ConnectionPool::Reaper:0x0055d30a607a88 @frequency=nil, @pool=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x0055d30a607b50 ...>>,
 @size=5,
 @spec=
  #<ActiveRecord::ConnectionAdapters::ConnectionSpecification:0x0055d30a5f2890
   @adapter_method="postgresql_connection",
   @config={:adapter=>"postgresql", :database=>"tod_test"},
   @name="primary">,
 @thread_cached_conns=#<Concurrent::Map:0x0055d30a607a38 entries=0 default_proc=nil>>
[4] pry(main)> ActiveRecord::Migration.create_table :orders do |t|
[4] pry(main)*   t.time :time  
[4] pry(main)*   t.timestamps null: false  
[4] pry(main)* end  
-- create_table(:orders)
   -> 0.0410s
=> #<PG::Result:0x0055d308a5bd20 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
[5] pry(main)> class Order < ActiveRecord::Base
[5] pry(main)*   serialize :time, Tod::TimeOfDay  
[5] pry(main)* end  
=> #<ActiveRecord::AttributeDecorators::TypeDecorator:0x0055d30aa58fd8
 @decorations=
  {"_time_zone_conversion"=>
    [#<Proc:0x0055d30a890fc0@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/time_zone_conversion.rb:78 (lambda)>,
     #<Proc:0x0055d30a890f70@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/time_zone_conversion.rb:79>],
   "_optimistic_locking"=>
    [#<Proc:0x0055d30a8901d8@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/locking/optimistic.rb:177 (lambda)>,
     #<Proc:0x0055d30a8901b0@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/locking/optimistic.rb:178>],
   "_time_serialize"=>
    [#<Proc:0x0055d30aa591b8@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_decorators.rb:12 (lambda)>,
     #<Proc:0x0055d30aa59208@/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/serialization.rb:60>]}>
[6] pry(main)> o = Order.new time: "12:00pm"
=> #<Order:0x0055d30aad7388 id: nil, time: #<Tod::TimeOfDay:0x0055d308583398 @hour=12, @minute=0, @second=0, @second_of_day=43200>, created_at: nil, updated_at: nil>
[7] pry(main)> o.time
=> #<Tod::TimeOfDay:0x0055d308583398 @hour=12, @minute=0, @second=0, @second_of_day=43200>
[8] pry(main)> o.save
=> true
[9] pry(main)> o.time
=> #<Tod::TimeOfDay:0x0055d3081cd618 @hour=12, @minute=0, @second=0, @second_of_day=43200>
[10] pry(main)> o.reload
=> #<Order:0x0055d30aad7388
 id: 1,
 time: #<Tod::TimeOfDay:0x0055d30ac11028 @hour=12, @minute=0, @second=0, @second_of_day=43200>,
 created_at: 2016-11-23 17:14:16 UTC,
 updated_at: 2016-11-23 17:14:16 UTC>
[11] pry(main)> o.time
=> #<Tod::TimeOfDay:0x0055d30ac11028 @hour=12, @minute=0, @second=0, @second_of_day=43200>
```

**Comment by kevinvangelder** [comment]
Sorry, it's been months and since I ran into issues I never committed the code. I'm in PST, so if you aren't that may be part of why you are unable to reproduce the issue.

**Comment by pedroadame** [comment]
Any update on this as of Rails 5.0.2 stable?

**Comment by jackc** [comment]
@pedroadame I have not been able to reproduce the above mentioned problems with Rails 5. The tests pass and I have not run into issues in my (limited) use with Rails 5. I would suggest trying it out.

**Comment by aiomaster** [comment]
I could not reproduce the problems with rails 5.1 and rails 5.2, so I think it just works now.
But it is important to have something like `config.active_record.time_zone_aware_types = [:datetime]` in your `application.rb` so that time fields don't get serialized by rails with the default `ActiveSupport::TimeWithZone`-class.

**Comment by jackc** [comment]
I just released `v3.0.0` which supports (and requires) Rails 6. So I'm going to close this issue now.
